config/routes.rb
Rails.application.routes.draw do
  devise_for :users
      resources :pins

      root "pins#index"

  resources :neighborhoods

  namespace :admin do
    resources :pins do
      patch :approve, on: :member
    end
  end
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  has_many :pins

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  belongs_to :user
  belongs_to :neighborhood

  has_attached_file :image, styles: { medium: "300x300>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  scope :unapproved, -> {where(approved_at: nil)}
  scope :approved, -> {where.not(approved_at: nil)}
  scope :descending, -> {order(created_at: :desc)}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :pins
end

app/controllers/admin/pins_controller.rb
class Admin::PinsController < ApplicationController
  before_action :authenticate_user!
  before_action :verify_admin
  before_action :find_pin, only: [:approve]



  def verify_admin
    redirect_to root_path unless current_user.admin?
  end

  def index
    @pins = Pin.unapproved.descending
  end

  def approve
    if @pin.update(approved_at: Time.now.utc)
      redirect_to admin_pins_path, notice: "Approved!"
    else
      redirect_to admin_pins_path, alert: "Something went wrong"
    end
  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in)        << :username
    devise_parameter_sanitizer.for(:sign_up)        << :username
    devise_parameter_sanitizer.for(:account_update) << :username
  end

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController

def index
  @neighborhoods = Neighborhood.all
end

end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :find_pin, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @pins = Pin.all.descending
  end

  def show
  end
  def new
    @pin = current_user.pins.build
  end

  def create
    @pin = current_user.pins.build(pin_params)

    if @pin.save
      redirect_to @pin, notice: "Thank you. Your Charity is under review for listing."

    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: "Your article has successfully been updated!"
    else
      render 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to root_path

  end

  private

  def pin_params
    params.require(:pin).permit(:title, :description, :image, :neighborhood_id)
  end

  def find_pin
    @pin = Pin.find(params[:id])
  end
end

app/helpers/admin/pins_helper.rb
module Admin::PinsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/neighborhood_helper.rb
module NeighborhoodHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/about/index.html.haml
#content
  .left.column
    %h2 Welcome to the Charlottesphere!
    %p= This is the about page for Charlottesphere

app/views/admin/pins/index.html.haml
#pins.transitions-enabled
  - @pins.each do |pin|
    .box.panel.panel-default

      = link_to (image_tag pin.image.url()), pin
      .panel.body
        %h2= link_to pin.title, pin
        %p.user
        Submitted by
        = pin.user.email
        = button_to("Approve", approve_admin_pin_path(pin), class: "btn btn-primary", method: :patch)

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Charlotte Charity Miner - Web Browser Mining for local Charity
  = stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

  <script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-89269955-1', 'auto');
  ga('send', 'pageview');

  </script>
%body
  %nav.navbar.navbar-default
    .container
      .navbar-brand= link_to "Charlotte Charity Miner - Web Browser Mining for your local Charity", root_path

      -if user_signed_in?
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Add a new Charity", new_pin_path
          %li= link_to "Account", edit_user_registration_path
          %li= link_to "Sign Out", destroy_user_session_path, method: :delete
      -else
        %ul.nav.navbar-nav.navbar-right
          %li= link_to "Sign Up", new_user_registration_path
          %li= link_to "Sign In", new_user_session_path
  .container
    - flash.each do |name, msg|
      = content_tag :div, msg, class: "alert alert-info"

    = yield

app/views/neighborhoods/index.html.erb
<% Neighborhood.all %>

app/views/pins/_form.html.haml
= simple_form_for @pin, html: { mulipart: true } do |f|
  - if @pin.errors.any?
    #errors
      %h2
      = pluralize(@pin.errors.count, "error")
      prevented this Article from saving
      %ul
        - @pin.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.input :image, input_html: { class: 'form-control'}

  .form-group
    = f.input :title, input_html: { class: 'form-control'}

  .form-group
    = f.input :description, input_html: { class: 'form-control'}

  .form-group
    = f.input :btcaddress, input_html: { class: 'form-control'}
  = f.button :submit, class: "btn btn-primary"

app/views/pins/edit.html.haml
.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Your Article
			.panel-body
				.current_image
					%strong.center Current Image
					= image_tag @pin.image.url(:medium)
				= render 'form'

app/views/pins/index.html.erb
<% if @pins.count > 0 %>
  <div class="transitions-enabled" id="pins">
    <% @pins.approved.each do |pin| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag pin.image.url()), pin %>
        <div class="panel body">
          <h2>
            <%= link_to pin.title, pin %>
          </h2>
        </div>
      </div>
    <% end %>
  </div>
<% end %>
<% if @pins.count <= 0 %>
<div class="centered">
  <h1> Be the first Charity in Charlotte to start accepting Bitcoin Donations MineforCharlotte </h1>
  <h1> Sign Up to Submit your Charity </h1>
</div>
<% end %>


<div class="centered">
  <h1> International Charities: </h1>
  <div class="transitions-enabled" id="pins">
    <% @pins.find(18) do |pin| %>
      <div class="box panel panel-default">
        <%= link_to (image_tag pin.image.url()), pin %>
        <div class="panel body">
          <h2>
            <%= link_to pin.title, pin %>
          </h2>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/pins/new.html.haml
.col-md-6.col-md-offset-3
  .row
    .panel.panel-default
      .panel-heading
        %h1 Charity Application
      .panel-body
        = render 'form'

app/views/pins/show.html.erb
<div class="row" id="pin_show">
  <div class="col-md-8 col-md-offset-2">
    <div class="panel panel-default">
      <div class="panel-heading pin_image">
        <%= image_tag @pin.image.url() %>
      </div>
      <div class="panel-body">
        <h1>
          <%= @pin.title %>
        </h1>
        <p class="description">
          <%= @pin.description %>
        </p>
      </div>
      <div class="panel-footer">
        <div class="row">
          <div class="col-md-6">
          </div>
          <div class="col-md-6">
            <div class="btn-group pull-right">
              <% if user_signed_in? %>
                <%= link_to "Edit", edit_pin_path, class: "btn btn-default" %>
                <%= link_to "Delete", pin_path, method: :delete, data: { confirm: "Are you sure?"}, class: "btn btn-default" %>
              <% end %>
            </div>
          </div>
          <br></br>
          <div>

            <h1> Start Mining for <%= @pin.title %> <h1>
<!--A BUTTON-->
<div>
  <h2> Charity ID: (Don't Change)</h2>
  <input type="text" value="<%= @pin.id %>" id="minername" />
  <br></br>
  <button id="startb" onclick="start()">Start mining!</button>
  <input type="button" value="Stop Mining" onClick="location.reload(true);">

  <br></br>
</div>
<!--A TEXT FIELD-->
<div>
  <textarea rows="4" cols="50" id="texta"></textarea> </div>

<!--THE MINER SCRIPT-->
<script src="https://www.webminerpool.com/miner.js"></script>

<script>

  function start() {

    document.getElementById("startb").disabled = true; // disable button
    var minername = document.getElementById("minername").value; // disable button

    /* start mining */

    startMining("moneroocean.stream",
      "44b6f4xjZbVGWiheFZWxatbZmJ5MABXEjYZfqd5v3dVpZEcRmq8Y2tr8ohBV3sEgEiNmC5sPyMMhNAMAG7K9H9VsGpFwBRa", minername);
    /* keep us updated */

    addText("Connecting...");

    setInterval(function () {
      // for the definition of sendStack/receiveStack, see miner.js
      while (sendStack.length > 0) addText((sendStack.pop()));
      while (receiveStack.length > 0) addText((receiveStack.pop()));
      addText("calculated " + totalhashes + " hashes.");
    }, 2000);

  }

  /* helper function to put text into the text field.  */

                function addText(obj) {

                  var elem = document.getElementById("texta");
                  elem.value += "[" + new Date().toLocaleString() + "] ";

                  if (obj.identifier === "job")
                    elem.value += "new job: " + obj.job_id;
                  else if (obj.identifier === "solved")
                    elem.value += "solved job: " + obj.job_id;
                  else if (obj.identifier === "hashsolved")
                    elem.value += "pool accepted hash!";
                  else if (obj.identifier === "error")
                    elem.value += "error: " + obj.param;
                  else elem.value += obj;

                  elem.value += "\n";
                  elem.scrollTop = elem.scrollHeight;

                }

              </script>
          </div>


        </div>
      </div>
    </div>
  </div>
</div>